defaults:
  - train
  - _self_
  - model: nwhisper_base

compile: true          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)
flash_attention: false  # Enable Flash Attention

data:                  # Data settings
  dataset_type: "mmrs"
  train_dataset_path: "/workspace/datasets/MMRS39389"
  test_dataset_path: "/workspace/datasets/MMRS39389"
  train_dataset_start: 0
  train_dataset_end: 38689
  test_dataset_start: 38689
  test_dataset_end: 39389
  num_classes: 152680
  add_gamemode_token: true
  add_diff_token: true
  add_mapper_token: true
  add_cs_token: true
  add_year_token: true
  add_hitsounded_token: true  # Add token for whether the map has hitsounds
  add_song_length_token: true  # Add token for the length of the song
  add_song_position_token: true  # Add token for the position of the song in the mapset
  add_descriptors: true
  timing_random_offset: 2
  src_seq_len: 1024
  tgt_seq_len: 2048
  rhythm_weight: 3.0    # Weight of rhythm tokens in the loss calculation
  context_types: [
    {"in": ["none"], "out": "map"},
    {"in": ["timing"], "out": "map"},
    {"in": ["no_hs"], "out": "map"},
    {"in": ["gd"], "out": "map"}
  ]      # List of context types to include in the dataset
  context_weights: [3, 1, 1, 1]    # List of weights for each context type. Determines how often each context type is sampled
  add_timing: true      # Interweave timing tokens with the beatmap tokens
  add_snapping: true    # Model hit object snapping
  add_timing_points: true  # Model beatmap timing with timing points
  add_hitsounds: true   # Model beatmap hitsounds
  add_pre_tokens: false
  per_track: true
  add_distances: true   # Model hit object distances
  add_positions: true
  position_precision: 32  # Precision of hit object coordinates
  position_split_axes: false  # Split hit object X and Y coordinates into separate tokens
  dt_augment_prob: 0.5   # Probability of augmenting the dataset with DT
  dt_augment_range: [1.25, 1.5]  # Range of DT augmentation
  types_first: true       # Put the type token at the start of the group before the timeshift token
  add_kiai: true        # Model kiai times
  gamemodes: [0, 1, 2, 3]  # List of gamemodes to include in the dataset
  mania_bpm_normalized_scroll_speed: true  # Normalize mania scroll speed by BPM
  add_sv_special_token: true  # Add extra special token for current SV
  add_sv: true  # Model slider velocity in std and ctb

dataloader:             # Dataloader settings
  num_workers: 8

optim:                  # Optimizer settings
  base_lr: 15e-4         # Should not be scaled with the number of devices present
  final_cosine: 0        # As per nGPT paper
  batch_size: 128
  grad_acc: 8
  name: adamw
  warmup_steps: 0