defaults:
  - train
  - _self_
  - model: t5_small_v4

compile: false          # PyTorch 2.0 optimization
precision: 'no'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  max_pre_token_len: 4
  timing_random_offset: 2
  rhythm_weight: 4.0    # Weight of rhythm tokens in the loss calculation
  sample_weights_path: "../../../rcomplexion/rhythm_complexities.csv"    # Path to sample weights

dataloader:             # Dataloader settings
  num_workers: 8

optim:                  # Optimizer settings
  base_lr: 5e-3         # Should be scaled with the number of devices present
  batch_size: 128
  grad_acc: 4