defaults:
  - train
  - _self_
  - model: t5_small_v4

compile: false          # PyTorch 2.0 optimization
precision: 'no'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  add_pre_tokens: false
  timing_random_offset: 2
  lookback: 0.5             # Fraction of audio sequence to fill with tokens from previous inference window
  lookahead: 0.4            # Fraction of audio sequence to skip at the end of the audio window

dataloader:             # Dataloader settings
  num_workers: 3

optim:                  # Optimizer settings
  base_lr: 1e-2         # Should be scaled with the number of devices present
  batch_size: 128
  grad_acc: 8