defaults:
  - train
  - _self_
  - model: t5_small_v9

compile: true          # PyTorch 2.0 optimization
precision: 'no'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  timing_random_offset: 2
  tgt_seq_len: 512
  rhythm_weight: 2.0    # Weight of rhythm tokens in the loss calculation
  sample_weights_path: "../../../datasets/rhythm_complexities.csv"    # Path to sample weights

dataloader:             # Dataloader settings
  num_workers: 8

optim:                  # Optimizer settings
  base_lr: 1e-2         # Should be scaled with the number of devices present
  batch_size: 128
  grad_acc: 4