name: mapperatorinator
services:
    mapperatorinator:
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
        - .:/workspace/Mapperatorinator
        network_mode: host
        container_name: mapperatorinator_space
        shm_size: 8gb
        build: .
        # image: my_fixed_image
        command: /bin/bash
        environment:
          - PROJECT_PATH=/workspace/Mapperatorinator
          - WANDB_API_KEY=${WANDB_API_KEY}