preprocess:
  sample_rate: 16000
  fft_length: 2048
  hop_length: 160
  mel_bins: 512
  log_scale: True
model:
  d_model: 512
  n_token: 256
  n_encoder_layer: 8
  n_decoder_layer: 8
  n_head: 6
  n_hidden: 1024
  dropout: 0.1
