defaults:
  - model
  - _self_

name: 'olibomby/nwhisper-base'
input_features: true
do_style_embed: false
config_base: 'openai/whisper-base'
overwrite:
  tie_word_embeddings: false
  manual_norm_weights: true
