defaults:
  - model
  - _self_

name: 'olibomby/nwhisper-base'
input_features: true
do_style_embed: false
embed_decoder_input: false
manual_norm_weights: true

overwrite:
  tie_word_embeddings: false
  manual_norm_weights: true
