defaults:
  - base_inference
  - inference
  - osut5: train_v20
  - diffusion: v1
  - _self_

version: 'Mapperatorinator V20'        # Beatmap version
timeshift_bias: -1.5        # Logit bias for sampling timeshift tokens
diff_ckpt: 'OliBomby/osu-diffusion-v2'
max_batch_size: 8
