defaults:
  - base_inference
  - inference
  - osut5: train_v19
  - diffusion: v1
  - _self_

version: 'Mapperatorinator V19'        # Beatmap version
timeshift_bias: -1.5        # Logit bias for sampling timeshift tokens

# Diffusion settings
generate_positions: false      # Use diffusion to generate object positions
