defaults:
  - base_inference
  - inference
  - osut5: train_v26
  - diffusion: v1
  - _self_

model_path: './test/ckpt_v26'  # Path to trained model
version: 'Mapperatorinator V26'        # Beatmap version
diff_ckpt: 'OliBomby/osu-diffusion-v2'
max_batch_size: 8
