defaults:
  - base_inference
  - inference
  - osut5: train_tiny_dist8
  - diffusion: v1
  - _self_

model_path: './test/tiny-dist8/'  # Path to trained model
diff_ckpt: 'OliBomby/osu-diffusion-v2'
version: 'Mapperatorinator tiny dist8'
in_context: []
output_type: [MAP]    # Output type (map, timing)
temperature: 0.9        # Sampling temperature
top_p: 0.9              # Top-p sampling threshold
max_batch_size: 32       # Maximum batch size for inference
generate_positions: false
timesteps: [10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  # The number of timesteps we want to take from equally-sized portions of the original process