defaults:
  - default
  - ../train@train: v21
  - ../diffusion@diffusion: v1
  - _self_

model_path: './test/ckpt_v21'  # Path to trained model
version: 'Mapperatorinator V21'        # Beatmap version
timeshift_bias: -1.5        # Logit bias for sampling timeshift tokens
diff_ckpt: 'OliBomby/osu-diffusion-v2'
max_batch_size: 8
