defaults:
  - default
  - ../train@train: v28
  - ../diffusion@diffusion: v1
  - _self_

model_path: 'OliBomby/Mapperatorinator-v28'
diff_ckpt: 'OliBomby/osu-diffusion-v2'
version: 'Mapperatorinator V28'        # Beatmap version
output_type: [TIMING, KIAI, MAP, SV]    # Output type (map, timing)
super_timing: true     # Use super timing generator (slow but accurate timing)
timing_leniency: 3     # Number of milliseconds of error to allow for timing generation
max_batch_size: 8