name: 'google/t5-v1_1-small'
overwrite:
  dropout_rate: 0.0
add_config:
  sample_rate: ${..spectrogram.sample_rate}
  hop_length: ${..spectrogram.hop_length}
  n_fft: ${..spectrogram.n_fft}
  n_mels: ${..spectrogram.n_mels}
  num_classes: ${..style.num_classes}
  class_dropout_prob: ${..style.class_dropout_prob}

max_seq_len: 512
max_target_len: 512
spectrogram:
  sample_rate: 16000
  hop_length: 128
  n_fft: 1024
  n_mels: 512
style:
  num_classes: 64821
  class_dropout_prob: 0.2