defaults:
  - inference
  - osut5: train_v10
  - diffusion: v1
  - _self_

version: 'osuT5 V10'        # Beatmap version
lookback: 0.5             # Fraction of audio sequence to fill with tokens from previous inference window
