seed: 42

train:
  total_steps: 300000
  session_steps: 40000
  warmup_steps: 1000
  lr: 0.0003
  resume: False
  resume_checkpoint_path: "./lightning_logs/version_{}/epoch_{}_step.ckpt"

val:
  interval: 1000
  batches: 50

dataset:
  train: "./dataset/train"
  val: "./dataset/validate"
  batch_size: 32
  num_workers: 4
  src_seq_len: 512
  tgt_seq_len: 256

osz_loader:
  min_difficulty: 0
  max_difficulty: 10
  mode: "max"

spectrogram:
  sample_rate: 16000
  hop_length: 128
  n_fft: 2048
  n_mels: 512

model:
  d_model: 512
  n_encoder_layer: 6
  n_decoder_layer: 6
  n_head: 8
  n_hidden: 1024
  dropout: 0.1
