seed: 42

train:
  num_steps: 300_000
  warmup_steps: 1000
  lr: 0.001

dataset:
  train: "./data/train"
  val: "./data/val"
  batch_size: 2
  num_workers: 2
  src_seq_len: 511
  tgt_seq_len: 256

osz_loader:
  min_difficulty: 0
  max_difficulty: 10
  mode: "center"

spectrogram:
  sample_rate: 16000
  hop_length: 128
  n_fft: 2048
  n_mels: 512

model:
  d_model: 512
  n_encoder_layer: 8
  n_decoder_layer: 8
  n_head: 8
  n_hidden: 1024
  dropout: 0.1
