defaults:
  - base_fid
  - inference_v31@inference
  - _self_

compile: false
num_processes: 3
seed: 0

skip_generation: false
fid: true
rhythm_stats: true

dataset_path: /workspace/datasets/ORS16291
dataset_start: 16200
dataset_end: 16291

classifier_ckpt: 'OliBomby/osu-classifier'

inference:
  super_timing: false

hydra:
  job:
    chdir: True
  run:
    dir: ./logs_fid/${now:%Y-%m-%d}/${now:%H-%M-%S}
