defaults:
  - base_fid
  - inference_tiny_dist@inference
  - _self_

compile: false
pad_sequence: true
num_processes: 3
seed: 0

dataset_path: /workspace/datasets/ORS16291
dataset_start: 16200
dataset_end: 16291

classifier_ckpt: 'OliBomby/osu-classifier'

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
