defaults:
  - inference
  - _self_
  - model: t5_small

version: 'osuT5 V1'        # Beatmap version

data:                  # Data settings
  center_pad_decoder: true            # Center pad decoder input