defaults:
  - base_inference
  - inference
  - osut5: train_v23
  - diffusion: v1
  - _self_

version: 'Mapperatorinator V23'        # Beatmap version
super_timing: true     # Use super timing generator (slow but accurate timing)
timing_leniency: 3     # Number of milliseconds of error to allow for timing generation
