defaults:
  - inference
  - osut5: train_v21
  - diffusion: v1
  - _self_

version: 'Mapperatorinator V21'        # Beatmap version
timeshift_bias: -1.5        # Logit bias for sampling timeshift tokens
