defaults:
  - inference
  - _self_
  - model: t5_small_v4

version: 'osuT5 V7'        # Beatmap version

data:                  # Data settings
  src_seq_len: 512
  tgt_seq_len: 256
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  add_pre_tokens: false
  sequence_stride: 0.5             # Fraction of audio sequence length to shift inference window