defaults:
  - inference
  - osut5: train_v7
  - diffusion: v1
  - _self_
  - model: t5_base

version: 'osuT5 V7'        # Beatmap version
sequence_stride: 0.5             # Fraction of audio sequence length to shift inference window
