defaults:
  - base_inference
  - inference
  - osut5: train_v28
  - diffusion: v1
  - _self_

model_path: 'OliBomby/Mapperatorinator-v28'
version: 'Mapperatorinator V28'        # Beatmap version
output_type: [TIMING, KIAI, MAP, SV]    # Output type (map, timing)
