model_path: ''          # Path to trained model
audio_path: ''          # Path to input audio
output_path: ''         # Path to output directory
beatmap_path: ''        # Path to .osu file to autofill metadata
other_beatmap_path: ''  # Path to .osu file of other beatmap in the mapset to use as reference
lookback: 0             # Fraction of audio sequence to fill with tokens from previous inference window
lookahead: 0            # Fraction of audio sequence to skip at the end of the audio window
beatmap_id: -1          # Beatmap ID to use as style
difficulty: -1          # Difficulty star rating to map
mapper_id: -1           # Mapper ID to use as style
descriptors: []         # List of descriptors to use for style
timing_leniency: 20     # Number of milliseconds of error to allow for timing generation
context_type: ''        # Context type of other beatmap
seed: 0                 # Random seed
cfg_scale: 1.0              # Scale of classifier-free guidance
temperature: 1.0        # Sampling temperature
top_p: 0.9              # Top-p sampling threshold
timeshift_bias: 0.0        # Logit bias for sampling timeshift tokens

bpm: 120                # Beats per minute of input audio
offset: 0               # Start of beat, in miliseconds, from the beginning of input audio
slider_multiplier: 1.8  # Multiplier for slider velocity
title: ''               # Song title
artist: ''              # Song artist
creator: 'osuT5'        # Beatmap creator
version: 'osuT5'        # Beatmap version

# Diffusion settings
generate_positions: false      # Use diffusion to generate object positions
compile: true          # PyTorch 2.0 optimization
diff_ckpt: ''                  # Path to checkpoint for diffusion model
diff_refine_ckpt: ''           # Path to checkpoint for refining diffusion model
beatmap_idx: 'osu_diffusion/beatmap_idx.pickle'  # Path to beatmap index
style_id: -1                # Style ID to use for diffusion
refine_iters: 10                  # Number of refinement iterations
random_init: true           # Whether to initialize with random noise instead of positions generated by the previous model
timesteps: [1000]  # The number of timesteps we want to take from equally-sized portions of the original process

hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}