defaults:
  - inference
  - osut5: train_v9
  - diffusion: v1
  - _self_

version: 'osuT5 V9'        # Beatmap version
sequence_stride: 0.5             # Fraction of audio sequence length to shift inference window
