model_path: ''          # Path to trained model
audio_path: ''          # Path to input audio
output_path: ''         # Path to output directory
bpm: 120                # Beats per minute of input audio
offset: 0               # Start of beat, in miliseconds, from the beginning of input audio
slider_multiplier: 1.8  # Multiplier for slider velocity
title: ''               # Song title
artist: ''              # Song artist
beatmap_path: ''        # Path to .osu file which will be remapped
other_beatmap_path: ''  # Path to .osu file of other beatmap in the mapset to use as reference
beatmap_id: -1          # Beatmap ID to use as style
difficulty: -1           # Difficulty star rating to map
creator: 'osuT5'        # Beatmap creator
version: 'osuT5'        # Beatmap version

data:                  # Data settings
  src_seq_len: 512
  tgt_seq_len: 384
  sample_rate: ${model.spectrogram.sample_rate}
  hop_length: ${model.spectrogram.hop_length}
  sequence_stride: 1             # Fraction of audio sequence length to shift inference window
  center_pad_decoder: false            # Center pad decoder input
  special_token_len: 0
  diff_token_index: -1
  style_token_index: -1
  max_pre_token_len: -1
  add_pre_tokens: true
  add_gd_context: false  # Prefix the decoder with tokens of another beatmap in the mapset

hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}