model_path: ''          # Path to trained model
audio_path: ''          # Path to input audio
output_path: ''         # Path to output directory
beatmap_path: ''        # Path to .osu file to autofill metadata
other_beatmap_path: ''  # Path to .osu file of other beatmap in the mapset to use as reference
lookback: 0             # Fraction of audio sequence to fill with tokens from previous inference window
lookahead: 0            # Fraction of audio sequence to skip at the end of the audio window
beatmap_id: -1          # Beatmap ID to use as style
difficulty: -1           # Difficulty star rating to map

bpm: 120                # Beats per minute of input audio
offset: 0               # Start of beat, in miliseconds, from the beginning of input audio
slider_multiplier: 1.8  # Multiplier for slider velocity
title: ''               # Song title
artist: ''              # Song artist
creator: 'osuT5'        # Beatmap creator
version: 'osuT5'        # Beatmap version

# Diffusion settings
generate_positions: false      # Use diffusion to generate object positions
diff_ckpt: ''                  # Path to checkpoint for diffusion model
diff_refine_ckpt: ''           # Path to checkpoint for refining diffusion model
beatmap_idx: 'osu_diffusion/beatmap_idx.pickle'  # Path to beatmap index
style_id: -1                # Style ID to use for diffusion
num_sampling_steps: 1000    # Number of sampling steps
cfg_scale: 1.0              # Scale of classifier-free guidance
refine_iters: 10                  # Number of refinement iterations

hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}