defaults:
  - inference
  - osut5: train_v10_gd
  - diffusion: v1
  - _self_

version: 'osuT5 V10.1 GD'        # Beatmap version
lookback: 0.4             # Fraction of audio sequence to fill with tokens from previous inference window
lookahead: 0.4            # Fraction of audio sequence to skip at the end of the audio window
