defaults:
  - train
  - _self_
  - model: t5_small_v4

compile: false          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  src_seq_len: 512
  tgt_seq_len: 256
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  add_pre_tokens: false
  timing_random_offset: 10

dataloader:             # Dataloader settings
  num_workers: 3

optim:                  # Optimizer settings
  batch_size: 128
  grad_acc: 8