defaults:
  - train
  - _self_
  - model: t5_base

compile: true          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  src_seq_len: 1024
  tgt_seq_len: 512
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  max_pre_token_len: 4
  timing_random_offset: 0

dataloader:             # Dataloader settings
  num_workers: 8

optim:                  # Optimizer settings
  batch_size: 128
  grad_acc: 8