defaults:
  - train
  - _self_
  - model: t5_small

data:                  # Data settings
  center_pad_decoder: true            # Center pad decoder input
  add_empty_sequences: false
  add_empty_sequences_at_step: 35000

logging:                # Logging settings
  every_steps: 100