defaults:
  - train
  - _self_
  - model: t5_base

compile: true          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  src_seq_len: 1024
  tgt_seq_len: 512
  special_token_len: 2
  diff_token_index: 0
  style_token_index: 1
  max_pre_token_len: 4
  timing_random_offset: 0
  train_dataset_path: '/root/ORS100'  # Training dataset directory
  train_dataset_start: 0  # Training dataset start index
  train_dataset_end: 90    # Training dataset end index
  test_dataset_path: '/root/ORS100'   # Testing/validation dataset directory
  test_dataset_start: 90   # Testing/validation dataset start index
  test_dataset_end: 100     # Testing/validation dataset end index

dataloader:             # Dataloader settings
  num_workers: 4

optim:                  # Optimizer settings
  batch_size: 128
  grad_acc: 32
#  base_lr: 4e-2         # Should be scaled with the number of devices present
#  final_cosine: 2e-5

logging:                # Logging settings
  every_steps: 1