defaults:
  - train
  - _self_
  - model: t5_small

compile: false          # PyTorch 2.0 optimization
precision: 'no'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  tgt_seq_len: 512
  center_pad_decoder: true            # Center pad decoder input

dataloader:             # Dataloader settings
  num_workers: 3

optim:                  # Optimizer settings
  batch_size: 128
  grad_acc: 8