compile: true
device: gpu
precision: 'bf16'              # Precision
seed: 0                     # Global seed
checkpoint_path: ''                          # Checkpoint path

model: 'DiT-B'                    # Model architecture
noise_schedule: 'squaredcos_cap_v2'          # Noise schedule
l1_loss: false                    # L1 loss
diffusion_steps: 1000             # Number of diffusion steps

data:
  train_dataset_path: '/workspace/datasets/ORS16291/'               # Path to the data
  num_classes: 64821          # Number of classes stored in the model
  end: 16291
  start: 0
  seq_len: 128                      # Sequence length
  stride: 16                        # Stride

dataloader:             # Dataloader settings
  num_workers: 4

optim:                  # Optimizer settings
  name: adamw
  base_lr: 1e-4
  batch_size: 256       # Global batch size
  total_steps: 400000
  warmup_steps: 0
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_acc: 2
  final_cosine: 1e-4

checkpoint:             # Checkpoint settings
  every_steps: 50000

logging:                # Logging settings
  log_with: 'wandb'     # Logging service (wandb/tensorboard)
  every_steps: 10
  mode: 'offline'

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
