defaults:
  - default
  - ../model@model: whisper_base
  - _self_

compile: true          # PyTorch 2.0 optimization
precision: 'bf16'         # Enable mixed precision (no/fp16/bf16/fp8)

data:                  # Data settings
  train_dataset_path: "/workspace/datasets/ORS16291"
  test_dataset_path: "/workspace/datasets/ORS16291"
  # All Special Prefix Tokens
  add_out_context_types: false  # Add tokens indicating types of the out context
  add_gamemode_token: false
  add_style_token: false
  add_diff_token: true
  add_mapper_token: true
  add_year_token: false
  add_hitsounded_token: false  # Add token for whether the map has hitsounds
  add_song_length_token: false  # Add token for the length of the song
  add_global_sv_token: false  # Add token for the global slider velocity in std and ctb
  add_cs_token: false
  add_keycount_token: false  # Add token for the number of keys in mania
  add_hold_note_ratio_token: false  # Add token for the ratio of hold notes in mania
  add_scroll_speed_ratio_token: false  # Add token for the scroll speed ratio in mania
  add_descriptors: true  # Add beatmap descriptor tokens
  add_sv_special_token: false  # Add token for last SV value
  add_kiai_special_token: false  # Add token for last kiai state
  add_song_position_token: false  # Add token for the position of the song in the mapset
  # ---
  timing_random_offset: 2
  src_seq_len: 1024
  tgt_seq_len: 1536
  rhythm_weight: 3.0    # Weight of rhythm tokens in the loss calculation
  sample_weights_path: "../../../datasets/rhythm_complexities.csv"    # Path to sample weights
  context_types:       # List of context types to include in the dataset
    - "in": ['${context_type:none}']
      "out": ['${context_type:map}']
    - "in": ['${context_type:timing}']
      "out": ['${context_type:map}']
    - "in": ['${context_type:no_hs}']
      "out": ['${context_type:map}']
    - "in": ['${context_type:gd}']
      "out": ['${context_type:map}']
  context_weights: [3, 1, 1, 1]    # List of weights for each context type. Determines how often each context type is sampled
  descriptors_path: "../../../datasets/beatmap_descriptors.csv"   # Path to file with all beatmap descriptors
  mappers_path: "../../../datasets/beatmap_users.json"       # Path to file with all beatmap mappers
  add_timing: true      # Model beatmap timing
  add_snapping: true    # Model hit object snapping
  add_hitsounds: true   # Model beatmap hitsounds
  add_pre_tokens: false
  per_track: true
  add_distances: false   # Model hit object distances
  add_positions: true

dataloader:             # Dataloader settings
  num_workers: 8

optim:                  # Optimizer settings
  base_lr: 1e-2         # Should be scaled with the number of devices present
  batch_size: 128
  grad_acc: 8